@startuml sequence
title Управление задачами

actor Исполнитель as exec
boundary "Веб-интерфейс" as site
control TaskContoller as tcont
control TaskManagerService as tmserv
control TaskDao as tdao
database Database as db

activate exec
activate site
activate db
activate tcont
activate tmserv
activate tdao
exec -> site : Изменение состояния\nзадачи через GUI

alt запрос проходит\nвалидацию
site -> tcont : HTTP PUT запрос с\nJSON TaskDto в body
else запрос не прошел валидацию
site <-- tcont : Сообщение об ошибке в\nзапросе с кодом 400
exec <-- site : Отображение ошибки
end
tcont -> tmserv : updateTask(TaskDto)
tmserv -> tdao : findById(long)

alt сущность с указанным\nid существует
tdao -> db : SQL запрос на чтение
tdao <-- db : Результативная\nстрока
tmserv <-- tdao : Объект Task
tmserv -> tmserv : Преобразование TaskDto\nобъекта в Task объект
tmserv -> tdao : save(Task)
tdao -> db : SQL запрос на изменение
tdao <-- db : Id измененной строки
tdao -> tdao : findById(id)
tdao -> db : SQL запрос на чтение
tdao <-- db : Результативная\nстрока
tmserv <-- tdao : Объект Task
tmserv -> tmserv : Преобразование Task\nобъекта в TaskDto объект
tcont <-- tmserv : Объект TaskDto
site <-- tcont : HTTP ответ с кодом 200\nи новым объектом JSON в body
exec <-- site : Обновленное состояния\nзадачи в GUI
else сущность с указанным\nid не существует
tdao <-- db : Пустые строки
tmserv <-- tdao : null
tcont <-- tmserv : исключение NoSuchElementException
site <-- tcont : Сообщение об ошибке в\nзапросе с кодом 400
exec <-- site : Отображение ошибки
end

@enduml