@startuml sequence
title Управление правами доступа

actor Руководитель as user
boundary "Интерфейс" as site
control ProjectContoller as pcont
control ProjectAccessManagementService as amserv
control ProjectDao as pdao 
control UserDao as udao
database Database as db

activate user
activate site
activate db
activate pcont
activate amserv
activate pdao
activate udao

alt Запрос проходит валидацию
    user -> site : Изменение права доступа через GUI
    site -> pcont : JSON запрос на изменение\nправ доступа к проекту\nпользователем
else Запрос не проходит валидацию
    site <-- pcont : Сообщение об ошибке в запросе с кодом 400
    user <-- site : Отображение ошибки
end

pcont -> amserv : addUserToProject(userId: long, projectId: long)
amserv -> amserv : getAuthorizatedUser()
amserv -> udao : findById(id: long)
udao -> db : SQL запрос
udao <-- db : Результирующие строки
amserv <-- udao : User
amserv -> amserv : Проверка роли пользователя
alt Пользователь действительно является руководителем
    amserv -> pdao : findById(id: long)
    pdao -> db : SQL запрос
    pdao <-- db : Результирующие строки
    amserv <-- pdao : Project
    alt Проект с таким id существует
        amserv -> udao : findById(id: long)
        udao -> db : SQL запрос
        udao <-- db : Результирующие строки
        amserv <-- udao : User
        alt Пользователь с таким id существует
            amserv -> amserv : Добавить пользователя в проект
            amserv -> pdao : save(project: Project)
            pdao -> db : SQL запрос
            pdao <-- db : Результирующие строки
            amserv <-- pdao : Project
            pcont <-- amserv : ProjectDto
            site <-- pcont : Ответ с кодом 200
            user <-- site : Отображение изменений
        else Пользователь с таким id не существует
            pcont <-- amserv : NotFoundException
            site <-- pcont : Ответ с кодом 404
            user <-- site : Отображение ошибки
        end
    else Проект с таким id не существует
        pcont <-- amserv : NotFoundException
        site <-- pcont : Ответ с кодом 404
        user <-- site : Отображение ошибки
    end
else Пользователь не руководитель проекта
    pcont <-- amserv : PermissionDeniedException
    site <-- pcont : Ответ с кодом 403
    user <-- site : Отображение ошибки
end

@enduml