@startuml sequence
title Управление статистикой

actor Руководитель as user

boundary "Интерфейс" as site
control StatisticsController as scont
control TaskDao as tdao
control ProjectDao as pdao
control UserDao as udao
database Database as db

activate user
activate site
activate tdao
activate udao
activate db
activate scont
activate pdao

user -> site : Запрос статистики проекта пользователем
site -> scont : JSON-запрос с данными проекта,\nпо которому нужно получить статистику,\nи данными пользователя, который\nхочет получить статистику

alt Запрос верный
    scont -> udao : Формирование объекта AccessManagePolicy(sender: User, project: Project, 'Manager':String)
    udao 
else Запрос неверный
    site <- scont : 400 WrongStruct
    user <- site : Отображение ошибки
end





group Запрос статистики Руководителем
    manager -> site : Запрос статистики проекта/задач
    site -> scont : JSON запрос статистики
    scont -> tasker : getProjectStatistics(long projectId)
    tasker -> sserv : 
    sserv -> db : SQL запрос данных проекта
    
    
    
    
    
    
    db --> sserv : Данные проекта
    sserv --> tasker : Статистика проекта
    tasker -> tasker : Обработка в TaskDao
    tasker -->scont  : Передача обработанного
    scont --> site : JSON ответ с кодом 200
    site --> manager : Отображение статистики
end


@enduml
